#! /bin/sh
# /etc/init.d/garage

### BEGIN INIT INFO
# Provides:          garage
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the garage web server
# Description:       starts garage using start-stop-daemon
### END INIT INFO

case "$1" in
  start)
    sudo forever -l /home/pi/garage/daemon.log -a -o /home/pi/garage/out.log -e /home/pi/garage/error.log start /home/pi/garage/serial.js
    sleep 1
    ;;
  stop)
    sudo forever stop /home/pi/garage/serial.js
    sleep 1
    ;;
  *)
    echo "Usage: /etc/init.d/garage {start|stop}"
    exit 1
    ;;
esac

exit 0
